### ISSUE TITLE
Cannot update company, 

### ISSUE THREAD

**Issue by LenWebel** [GuibelTechnology/TheCargoTracker#8]
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at TCT.Address.Util.AddressUtil.ShouldAddressBeReset(Address address, AddressDto addressDto) in /Users/lenwebel/work/tct/Guibel-services/src/TCT.Application/Address/Util/AddressUtil.cs:line 9
   at TCT.Company.CompanyAppService.Update(CompanyDto input) in /Users/lenwebel/work/tct/Guibel-services/src/TCT.Application/Company/CompanyAppService.cs:line 121
   at Abp.Threading.InternalAsyncHelper.AwaitTaskWithPostActionAndFinallyAndGetResult[T](Task`1 actualReturnValue, Func`1 postAction, Action`1 finalAction)
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()
```

![image](https://user-images.githubusercontent.com/11282718/68097935-cf01fc80-fef4-11e9-8a50-f3796b138e48.png)

**Comment by LenWebel** [comment]
is address required ?
